// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCObinNwG1A9JqZA5FxqGbYB1AvnCuJsCY',
    appId: '1:1086070649703:web:a69c52e6424616f00735c2',
    messagingSenderId: '1086070649703',
    projectId: 'task-management-app-c6906',
    authDomain: 'task-management-app-c6906.firebaseapp.com',
    storageBucket: 'task-management-app-c6906.firebasestorage.app',
    measurementId: 'G-XL8NC4S4CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqKhwsjw5nHRZH7keE4g0lx6dBql1Lf38',
    appId: '1:1086070649703:android:65d117c99ffc9bac0735c2',
    messagingSenderId: '1086070649703',
    projectId: 'task-management-app-c6906',
    storageBucket: 'task-management-app-c6906.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiFKvn9P2321d2TUj-gJijuG_9s8WqYxY',
    appId: '1:1086070649703:ios:db8fa01830032e6a0735c2',
    messagingSenderId: '1086070649703',
    projectId: 'task-management-app-c6906',
    storageBucket: 'task-management-app-c6906.firebasestorage.app',
    iosBundleId: 'com.example.taskMangementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiFKvn9P2321d2TUj-gJijuG_9s8WqYxY',
    appId: '1:1086070649703:ios:db8fa01830032e6a0735c2',
    messagingSenderId: '1086070649703',
    projectId: 'task-management-app-c6906',
    storageBucket: 'task-management-app-c6906.firebasestorage.app',
    iosBundleId: 'com.example.taskMangementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCObinNwG1A9JqZA5FxqGbYB1AvnCuJsCY',
    appId: '1:1086070649703:web:703893b61058e0730735c2',
    messagingSenderId: '1086070649703',
    projectId: 'task-management-app-c6906',
    authDomain: 'task-management-app-c6906.firebaseapp.com',
    storageBucket: 'task-management-app-c6906.firebasestorage.app',
    measurementId: 'G-ZY5XC69XBY',
  );
}
